config/routes.rb
Rails.application.routes.draw do
  # Sessions
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Users
  get  '/register', to: 'users#new'
  post '/register', to: 'users#create'
  get '/profile', to: 'users#show'
  patch '/update_seller_status', to: 'users#update_seller_status'

  # Products
  resources :products do
    get 'order', to: 'orders#new', as: 'new_order'
    post 'order', to: 'orders#create'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :buyer

  validates :quantity, :total_price, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller
  has_many :orders

  validates :name, :description, :price, :stock, presence: true
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_one :buyer, dependent: :destroy
    has_one :seller, dependent: :destroy

    after_create :create_buyer

    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
  
    private
  
    # Renvoie l'utilisateur actuellement connecté (s'il y en a un)
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    # Vérifie si l'utilisateur est connecté
    def logged_in?
      current_user.present?
    end
  
    # Redirige vers la page de connexion si l'utilisateur n'est pas connecté
    def require_login
      unless logged_in?
        flash[:alert] = "You need to be logged in to access this page."
        redirect_to login_path
      end
    end

    def current_user_is_seller?
        current_user&.seller.present?
      end
    
    def require_seller
        unless current_user_is_seller?
          flash[:alert] = "You need to be a seller to access this page."
          redirect_to root_path
        end
    end 
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :require_login, :require_buyer, :not_seller_product 
  
  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    @order = current_user.buyer.orders.new(order_params)
    @order.product = @product
    @order.total_price = @product.price * @order.quantity

    if @order.save
      @product.update(stock: @product.stock - @order.quantity)
      flash[:notice] = "Your order has been placed successfully."
      redirect_to @product
    else
      flash[:alert] = "Your order could not be processed. Please try again."
      render :new
    end
  end
  
    private
  
    def order_params
      params.require(:order).permit(:quantity)
    end
  
    def require_buyer
      unless current_user.buyer
        flash[:alert] = "You need to be a buyer to access this page."
        redirect_to products_path
      end
    end

    def not_seller_product
      @product = Product.find(params[:product_id])
      if current_user.seller == @product.seller
        flash[:alert] = "You can't buy your own product."
        redirect_to products_path
      end
    end
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :require_login, except: [:index, :show]
    before_action :set_product, only: [:show, :edit, :update, :destroy]
  
    def index
      @products = Product.all
      @user = current_user
    end
  
    def new
      @product = Product.new
    end
  
    def create
        if current_user_is_seller?
          @product = current_user.seller.products.build(product_params)
          if @product.save
            redirect_to @product, notice: 'Product created successfully.'
          else
            render :new
          end
        else
          redirect_to root_path, alert: "You need to be a seller to create a product."
        end
      end
  
      def show
        @product = Product.find(params[:id])
      end
  
    def edit
    end
  
    def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product updated successfully.'
      else
        render :edit
      end
    end
  
    def destroy
      if(current_user.email != @product.seller.user.email)
        redirect_to products_url, alert: "You can't delete a product that you didn't create."
      else
        @product.destroy
        flash[:alert] = 'Product deleted successfully.'
        redirect_to products_path
      end
    end
  
    private
  
    def set_product
      @product = Product.find(params[:id])
    end
  
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock)
    end
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      render json: { error: 'Invalid email or password' }, status: :unauthorized
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show, :update_seller_status]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      if params[:user][:become_seller] == '1'
        @user.create_seller
      end
      redirect_to root_path, notice: 'Account created successfully.'
    else
      render :new
    end
  end

  def update_seller_status
    @user = current_user
    if params[:seller] == '1'
      @user.create_seller unless @user.seller.present?
      flash[:notice] = "You are now a seller."
    else
      @user.seller.destroy if @user.seller.present?
      flash[:notice] = "You are no longer a seller."
    end
    redirect_to profile_path
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def authenticate_user
    render json: { error: 'Not Authorized' }, status: :unauthorized unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceAppRaph</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
  
</html>

app/views/orders/new.html.erb
<h1>Passer une Commande pour <%= @product.name %></h1>

<p>
  <strong>Nom :</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description :</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Prix :</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Stock :</strong>
  <%= @product.stock %>
</p>

<%= form_with model: @order, url: product_order_path(@product), local: true do |form| %>
  <%= form.hidden_field :product_id, value: @product.id %>
  <div>
    <%= form.label :quantity, "Quantité" %>
    <%= form.number_field :quantity, value: 1, min: 1, max: @product.stock %>
  </div>
  <div>
    <%= form.submit "Acheter", class: "button" %>
  </div>
<% end %>

<%= link_to 'Retour aux détails du produit', product_path(@product) %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <% if @user != nil %>
          <% if @user.seller && current_user.email == product.seller.user.email %>
            <td><%= link_to 'Edit', edit_product_path(product), class: "button"%></td>
            <td><%= button_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure ?' }, class: "button" %>
</td>
          <% end %>
          <% if logged_in? && current_user.buyer && current_user.email != product.seller.user.email %>
            <td><%= link_to 'Order', product_new_order_path(product), class: "button" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>

<% if @user != nil %>
    <% if @user.seller %>
    <%= link_to 'New Product', new_product_path %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Add a Product</h1>

<%= form_with model: @product, local: true do |form| %>
  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, "Description" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price, "Price" %>
    <%= form.number_field :price, step: 0.01 %>
  </div>
  <div>
    <%= form.label :stock, "Stock Quantity" %>
    <%= form.number_field :stock %>
  </div>
  <div>
    <%= form.submit "Add" %>
  </div>
<% end %>

<%= link_to 'Back to Product List', products_path %>

app/views/products/show.html.erb
<h1>Product Details</h1>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @product.seller.user.email %>
</p>

<%= link_to 'Back to Product List', products_path %>

app/views/shared/_footer.html.erb
<% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to 'Home', root_path %>
  <% if logged_in? %>
    <%= link_to 'Logout', logout_path, method: :delete %>
    <%= link_to 'Profile', profile_path %>
  <% else %>
    <%= link_to 'Sign in', login_path %> |
    <%= link_to 'Sign up', register_path %>
  <% end %>
</nav>

app/views/users/new.html.erb
<h1>Register an account</h1>

<%= form_with model: @user, url: register_path, local: true do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation, "Password confirmation" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.check_box :become_seller %>
    <%= form.label :become_seller, "I want to become seller" %>
  </div>
  <div>
    <%= form.submit "Register" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Profil de <%= @user.email %></h1>

<p><strong>Email:</strong> <%= @user.email %></p>

<% if @user.buyer %>
  <p><strong>Type de compte:</strong> Acheteur</p>
<% end %>

<%= form_with url: update_seller_status_path, method: :patch, local: true do %>
  <div>
    <%= label_tag :seller, "Je suis un vendeur" %>
    <%= check_box_tag :seller, '1', @user.seller.present? %>
  </div>
  <div>
    <%= submit_tag "Mettre à jour", class: "button" %>
  </div>
<% end %>

<%= link_to 'Retour à la page d\'accueil', root_path %>